bookmark/urls.py
from django.urls import path
from .views import *
# from . import views

# url 이름을 가지고 패턴을 찾고자 할때 namespace를 사용하려면 app_name이 필수
app_name = 'bookmark'
urlpatterns = [
    # path('', list, name='list'),
    # re_path(regexp,'',''),
    # 함수형뷰 : 함수 이름만
    # 클래스형뷰 : 클래스 이름.as_view()
    path('list/', BookmarkListView.as_view(), name='list'),
    path('write/', BookmarkCreateView.as_view(), name='write'),
    # <1:2> : 1 - data type, 2 - data name
    path('update/<int:pk>', BookmarkUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', BookmarkDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>', BookmarkDetailView.as_view(), name='detail'),


#    path('list/', views.list, name='list'),
#    path('write/', views.write, name='write'),
#    path('update/', views.update, name='update'),
#    path('delete/', views.delete, name='delete'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('bookmark.urls')),
    path('admin/', admin.site.urls),
]

bookmark/models.py
from django.db import models

# Create your models here.
# 데이타베이스에 직접 접근하는 것이 아니라 ORM 기능을 통해서 접근
# 모델은 class 로 만듦

class Bookmark(models.Model):
    # 필드 : 데이터베이스에 어떤 컬럼, 어떤 형태, 어떤 제약조건
    # 필드목적2 : 프론트에서 어떤 form tag 와 어떤 제약조건을 설정
    site_name = models.CharField(max_length=100)
    url = models.URLField('Site URL')

    # print 함수를 사용해서 객체를 출력할때 출력될 내용을 변환하는 함수
    # 장고가 이걸 응용해서 화면에 객체를 html 로 출력할때 내용을 변환하는 함수
    def __str__(self):
        return self.site_name + " : " + self.url

    class Meta:
        # 해당 모델에 대한 옵션값
        # 정렬, 출력될 모델 이름, + : ascending - : descending
        ordering = ['site_name']

    # Todo : get_absolute_url
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('bookmark:detail', args=[str(self.id)])  # 'detail/3'

bookmark/views.py
from django.shortcuts import render

from django.http import HttpResponse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from .models import Bookmark
from django.urls import reverse_lazy

# Create your views here.
# view 종류 : 함수형, 클래스형
# 장고 목적 ? : 귀찮은거 하기 싫어서...
# 클래스형 : 자주 쓰는 기능을 상속받아서 간단하게 생성

# list view
class BookmarkListView(ListView):
    model = Bookmark
    # 클래스형 뷰는 기본적으로 렌더링할 템플릿 파일이 지정이 되어 있습니다.
    # bookmark/bookmark_list.html

class BookmarkCreateView(CreateView):
    model = Bookmark
    # 입력받을 필드 목록
    # default : _form
    template_name_suffix = '_create'
    fields = ['site_name', 'url']
    # get_absolute_url 을 자동으로 호출함
    success_url = reverse_lazy('list')

class BookmarkUpdateView(UpdateView):
    model = Bookmark
    template_name_suffix = '_update'
    fields = ['site_name', 'url']
    #success_url = reverse_lazy('detail')


class BookmarkDeleteView(DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:list')


class BookmarkDetailView(DetailView):
    model = Bookmark
    template_name_suffix = '_detail'

'''
def list(request):
    return HttpResponse("List")
def write(request):
    return HttpResponse("Write")

def update(request):
    return HttpResponse("Update")

def delete(request):
    return HttpResponse("Delete")
'''

bookmark/templates/bookmark/_bookmark_list.html
{% extends 'base.html' %}
{% block title %}Bookmark List{% endblock %}
{% block content %}
<!-- //
template syntax
{ %  % } : 기능태그
{ {  } } : 출력태그
// -->
<table>
    <tbody>
    {% for bookmark in object_list %}
    <tr>
        <td>
    {{ forloop.counter }}
        </td>
        <td>
    {{ bookmark.site_name }}
        </td>
        <td>
            <a href="{{ bookmark.url }}" target="_blank" class="btn btn-success">{{ bookmark.url }}</a>
        </td>
    </tr>

    {%  endfor %}
    </tbody>
</table>
{% endblock %}

bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Confirm Delete{% endblock %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div class="alert alert-danger">Do you want to delete bookmark "{{object}}"?</div>
    <input type="submit" value="Delete" class="btn btn-danger">
</form>
{% endblock %}

bookmark/templates/bookmark/bookmark_create.html
{% extends 'base.html' %}
{% block title %}Bookmarks{% endblock %}
{% block content %}
<form action="" method="post">
    <!-- // # cross-site script prevention // -->
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-success" value="write">
</form>
{% endblock %}

bookmark/templates/bookmark/bookmark_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

bookmark/templates/bookmark/bookmark_detail.html
{% extends 'base.html' %}
{% block title %}Bookmarks Detail{% endblock %}
{% block content %}
{{object.site_name}}
{{object.url}}
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends 'base.html' %}
{% block title %}Bookmarks List{% endblock %}
{% block content %}
<div class="btn-group d-block text-right mb-1" role="group">
  <a href="{% url 'bookmark:write' %}" class="btn btn-info">Add</a>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Site</th>
      <th scope="col">URL</th>
      <th scope="col">Modify</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for bookmark in object_list %}
        <tr>
            <td>
                {{ forloop.counter }}
            </td>
            <td>
                 <a href="{% url 'bookmark:detail' bookmark.id %}" target="_blank">{{bookmark.site_name}}</a>
            </td>
            <td>
                <a href="{{bookmark.url}}" target="_blank">{{bookmark.url}}</a>
            </td>
            <td>
                <a href="{% url 'bookmark:update' pk=bookmark.id %}" class="btn btn-success btn-sm">modify</a>
            </td>
            <td>
                <a href="{% url 'bookmark:delete' bookmark.id %}" class="btn btn-danger btn-sm">delete</a>
            </td>
        </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

bookmark/templates/bookmark/bookmark_update.html
{% extends 'base.html' %}
{% block title %}Bookmarks Update{% endblock %}
{% block content %}
<form action="" method="post">
    <!-- // # cross-site script prevention // -->
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-success" value="write">
</form>
{% endblock %}

templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</head>
<body>
<!-- //
공통된 영역
글로벌 네비게이션
사이드 메뉴
카드
로그인
하위 템플릿에서 사용할 블록
// -->
{% block content %}
{% endblock %}
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
<div class="container">
    <header class="py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">

          </div>
          <div class="col-4 text-center">
            <a class="header-logo text-dark" href="/list">Bookmark</a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="text-muted" href="#">
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3"><circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
            </a>
          </div>
        </div>
      </header>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>